/****** Script for SelectTopNRows command from SSMS  ******/
SET IDENTITY_INSERT [THLWToolBoxContext-088877b4-245d-43ef-b004-d1d23cc730e7].[dbo].[PlayerUnitData] ON;
INSERT INTO [THLWToolBoxContext-088877b4-245d-43ef-b004-d1d23cc730e7].[dbo].[PlayerUnitData] (
       [id]
      ,[name]
      ,[name_kana]
      ,[alias_name]
      ,[short_name]
      ,[person_id]
      ,[album_id]
      ,[role]
      ,[exp_id]
      ,[symbol_name]
      ,[symbol_title]
      ,[symbol_description]
      ,[life_point]
      ,[yang_attack]
      ,[yang_defense]
      ,[yin_attack]
      ,[yin_defense]
      ,[speed]
      ,[shot1_id]
      ,[shot2_id]
      ,[spellcard1_id]
      ,[spellcard2_id]
      ,[spellcard3_id]
      ,[spellcard4_id]
      ,[spellcard5_id]
      ,[skill1_id]
      ,[skill2_id]
      ,[skill3_id]
      ,[resist_id]
      ,[characteristic_id]
      ,[ability_id]
      ,[recycle_id]
      ,[default_costume_id]
      ,[drop_text]
      ,[limitbreak_item_id]
      ,[spellcard_bgm_id]
      ,[is_show]
)
SELECT * FROM UnitTableRaw where symbol_name != '(empty)' and (shot1_id != 10011 or id = 1001) and alias_name != '_TEST'
SET IDENTITY_INSERT [THLWToolBoxContext-088877b4-245d-43ef-b004-d1d23cc730e7].[dbo].[PlayerUnitData] OFF;